// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dllbzqbpsbfpiuekpmwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsbGJ6cWJwc2JmcGl1ZWtwbXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyOTM2MzcsImV4cCI6MjA3NDg2OTYzN30.ciO8ENIiLfWe9FKxsWCsptBQQVpByEZVoEo5A6pL-Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);